const MOCK = {
  JOBS: [
    {
      id: 1,
      title: 'Software Engineer',
      description: 'Develop and maintain software applications.',
      date: new Date('2024-05-01'),
      jobLink: 'https://www.linkedin.com/jobs/view/3700102746/',
      applyLink:
        'https://www.worldquant.com/career-listing/?application=4065713006',
      companyName: 'Google',
      companyLink: 'https://www.google.com',
      companyImageUrl:
        'https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png',
      location: 'Mountain View, CA',
      companyLocation:
        '1600 Amphitheatre Pkwy, Mountain View, CA 94043, United States',
      skills: ['JavaScript', 'Python'],
      keyword: 'Software',
      experienceLevel: 'Mid-Senior',
      time: 'Full-time',
      type: 'Full-time',
      workingMode: 'Remote',
      industry: 'IT & Media',
      platform: 'Linkedin',
    },
    {
      id: 2,
      title: 'Frontend Engineer',
      description: 'Create and improve user interfaces.',
      date: new Date('2024-05-01'),
      jobLink: 'https://www.linkedin.com/jobs/view/3700102746/',
      applyLink:
        'https://www.worldquant.com/career-listing/?application=4065713006',
      companyName: 'Meta',
      companyLink: 'https://www.facebook.com',
      companyImageUrl:
        'https://i.pinimg.com/originals/b7/06/fa/b706fa17832e8854ee125404a655f0df.jpg',
      location: 'Menlo Park, CA',
      companyLocation: '1 Hacker Wy, Menlo Park, CA 94025, United States',
      skills: ['React', 'CSS'],
      keyword: 'Frontend',
      experienceLevel: 'Mid-Senior',
      time: 'Full-time',
      type: 'Full-time',
      workingMode: 'On-site',
      industry: 'IT & Media',
      platform: 'Linkedin',
    },
    {
      id: 3,
      title: 'Cloud Engineer',
      description: 'Manage cloud infrastructure and services.',
      date: new Date('2024-05-01'),
      jobLink: 'https://www.linkedin.com/jobs/view/3700102746/',
      applyLink:
        'https://www.worldquant.com/career-listing/?application=4065713006',
      companyName: 'Amazon',
      companyLink: 'https://www.amazon.com',
      companyImageUrl:
        'https://cdn3.iconfinder.com/data/icons/social-media-2169/24/social_media_social_media_logo_amazon-256.png',
      location: 'Seattle, WA',
      companyLocation: '440 Terry Ave N, Seattle, WA 98109, United States',
      skills: ['AWS', 'DevOps'],
      keyword: 'Cloud',
      experienceLevel: 'Entry',
      time: 'Full-time',
      type: 'Full-time',
      workingMode: 'Hybrid',
      industry: 'IT & Media',
      platform: 'Indeed',
    },
    {
      id: 4,
      title: '.NET Developer',
      description: 'Develop applications using .NET framework.',
      date: new Date('2024-05-01'),
      jobLink: 'https://www.linkedin.com/jobs/view/3700102746/',
      applyLink:
        'https://www.worldquant.com/career-listing/?application=4065713006',
      companyName: 'Microsoft',
      companyLink: 'https://www.microsoft.com',
      companyImageUrl:
        'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/216_Microsoft_logo_logos-256.png',
      location: 'Redmond, WA',
      companyLocation: '1 Microsoft Wy, Redmond, WA 98052, United States',
      skills: ['C#', '.NET'],
      keyword: '.NET',
      experienceLevel: 'Intern',
      time: 'Full-time',
      type: 'Full-time',
      workingMode: 'Remote',
      industry: 'IT & Media',
      platform: 'TopCV',
    },
    {
      id: 5,
      title: 'IOS Engineer',
      description: 'Develop and maintain iOS applications.',
      date: new Date('2024-05-01'),
      jobLink: 'https://www.linkedin.com/jobs/view/3700102746/',
      applyLink:
        'https://www.worldquant.com/career-listing/?application=4065713006',
      companyName: 'Apple',
      companyLink: 'https://www.apple.com',
      companyImageUrl:
        'https://cdn4.iconfinder.com/data/icons/flat-brand-logo-2/512/apple-256.png',
      location: 'Cupertino, CA',
      companyLocation: '1 Apple Park Wy, Cupertino, CA 95014, United States',
      skills: ['Swift', 'Objective-C'],
      keyword: 'iOS',
      experienceLevel: 'Associate',
      time: 'Full-time',
      type: 'Full-time',
      workingMode: 'On-site',
      industry: 'IT & Media',
      platform: 'ITviec',
    },
  ],
  SAVE_JOBS: [
    {
      title: 'Software Engineer',
      description: 'Develop and maintain software applications.',
      date: new Date('2024-05-01'),
      jobLink: 'https://www.linkedin.com/jobs/view/3700102746/',
      applyLink:
        'https://www.worldquant.com/career-listing/?application=4065713006',
      companyName: 'Google',
      companyLink: 'https://www.google.com',
      companyImageUrl:
        'https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png',
      location: 'Mountain View, CA',
      companyLocation:
        '1600 Amphitheatre Pkwy, Mountain View, CA 94043, United States',
      skills: ['JavaScript', 'Python'],
      keyword: 'Software',
      experienceLevel: 'Mid-Senior',
      time: 'Full-time',
      type: 'Full-time',
      workingMode: 'Remote',
      industry: 'IT & Media',
      platform: 'Linkedin',
      status: 'SAVED',
      savedDate: new Date('2024-05-19'),
    },
    {
      title: 'Frontend Engineer',
      description: 'Create and improve user interfaces.',
      date: new Date('2024-05-01'),
      jobLink: 'https://www.linkedin.com/jobs/view/3700102746/',
      applyLink:
        'https://www.worldquant.com/career-listing/?application=4065713006',
      companyName: 'Meta',
      companyLink: 'https://www.facebook.com',
      companyImageUrl:
        'https://i.pinimg.com/originals/b7/06/fa/b706fa17832e8854ee125404a655f0df.jpg',
      location: 'Menlo Park, CA',
      companyLocation: '1 Hacker Wy, Menlo Park, CA 94025, United States',
      skills: ['React', 'CSS'],
      keyword: 'Frontend',
      experienceLevel: 'Mid-Senior',
      time: 'Full-time',
      type: 'Full-time',
      workingMode: 'On-site',
      industry: 'IT & Media',
      platform: 'Linkedin',
      status: 'INTERVIEWED',
      savedDate: new Date('2024-05-21'),
    },
    {
      title: 'Cloud Engineer',
      description: 'Manage cloud infrastructure and services.',
      date: new Date('2024-05-01'),
      jobLink: 'https://www.linkedin.com/jobs/view/3700102746/',
      applyLink:
        'https://www.worldquant.com/career-listing/?application=4065713006',
      companyName: 'Amazon',
      companyLink: 'https://www.amazon.com',
      companyImageUrl:
        'https://cdn3.iconfinder.com/data/icons/social-media-2169/24/social_media_social_media_logo_amazon-256.png',
      location: 'Seattle, WA',
      companyLocation: '440 Terry Ave N, Seattle, WA 98109, United States',
      skills: ['AWS', 'DevOps'],
      keyword: 'Cloud',
      experienceLevel: 'Entry',
      time: 'Full-time',
      type: 'Full-time',
      workingMode: 'Hybrid',
      industry: 'IT & Media',
      platform: 'Indeed',
      status: 'REJECTED',
      savedDate: new Date('2024-05-23'),
    },
  ],
  OPTIONS: {
    TIME: [
      { value: 'ANY', label: 'Any' },
      { value: 'DAY', label: 'Day' },
      { value: 'WEEK', label: 'Week' },
      { value: 'MONTH', label: 'Month' },
    ],
    TYPE: [
      { value: 'FULL_TIME', label: 'Full-Time' },
      { value: 'PART_TIME', label: 'Part-Time' },
      { value: 'TEMPORARY', label: 'Temporary' },
      { value: 'CONTRACT', label: 'Contract' },
      { value: 'INTERNSHIP', label: 'Internship' },
      { value: 'VOLUNTEER', label: 'Volunteer' },
      { value: 'OTHER', label: 'Other' },
    ],
    INDUSTRY: [
      { value: 'TECHNOLOGY_INFORMATION_AND_MEDIA', label: 'IT & Media' },
      { value: 'ACCOMMODATION_SERVICES', label: 'Accommodation' },
      { value: 'ADMINISTRATIVE_AND_SUPPOR_SERVICES', label: 'Admin Support' },
      { value: 'CONSTRUCTION', label: 'Construction' },
      { value: 'CONSUMER_SERVICES', label: 'Consumer Services' },
      { value: 'EDUCATION', label: 'Education' },
      { value: 'ENTERTAINMENT_PROVIDERS', label: 'Entertainment' },
      { value: 'FARMING_RANCHING_FORESTRY', label: 'Farming' },
      { value: 'FINANCIAL_SERVICES', label: 'Financial' },
      { value: 'GOVERNMENT_ADMINISTRATION', label: 'Government' },
      { value: 'HOSPITALS_AND_HEALTH_CARE', label: 'Health Care' },
      { value: 'MANUFACTURING', label: 'Manufacturing' },
      { value: 'PROFESSIONAL_SERVICES', label: 'Professional' },
      {
        value: 'REAL_ESTATE_AND_EQUIPMENT_RENTAL_SERVICES',
        label: 'Real Estate',
      },
      { value: 'RETAIL', label: 'Retail' },
    ],
    EXP_LEVEL: [
      { value: 'INTERNSHIP', label: 'Intern' },
      { value: 'ENTRY_LEVEL', label: 'Entry' },
      { value: 'ASSOCIATE', label: 'Associate' },
      { value: 'MID_SENIOR', label: 'Mid-Senior' },
      { value: 'DIRECTOR', label: 'Director' },
      { value: 'EXECUTIVE', label: 'Executive' },
    ],
    WORKING_MODE: [
      { value: 'ON_SITE', label: 'On-Site' },
      { value: 'REMOTE', label: 'Remote' },
      { value: 'HYBRID', label: 'Hybrid' },
    ],
    JOB_STATUS: [
      { value: 'SAVED', label: 'Saved' },
      { value: 'APPLIED', label: 'Applied' },
      { value: 'REJECTED', label: 'Rejected' },
      { value: 'INTERVIEWED', label: 'Interviewed' },
    ],
  },
  FILTERS: [
    {
      id: 1,
      name: 'Default',
      user: '60f9f1b6d9f7c8000f0f3b1d',
      location: 'Mountain View, CA',
      keyword: 'Software Engineer',
      experience_level: 'MID_SENIOR',
      working_mode: 'REMOTE',
      type: 'FULL_TIME',
      industry: 'TECHNOLOGY_INFORMATION_AND_MEDIA',
      time: 'DAY',
      excludeTitles: 'senior;lead',
      excludeCompanies: 'netflix;facebook',
      includeDescription: 'ai;developer',
      excludeDescription: 'senior;lead',
      active: true,
    },
    {
      id: 2,
      name: 'Frontend Dev',
      user: '60f9f1b6d9f7c8000f0f3b1d',
      location: 'Menlo Park, CA',
      keyword: 'Frontend Engineer',
      experience_level: 'ENTRY_LEVEL',
      working_mode: 'ON_SITE',
      type: 'FULL_TIME',
      industry: 'TECHNOLOGY_INFORMATION_AND_MEDIA',
      time: 'WEEK',
      excludeTitles: 'senior;lead',
      excludeCompanies: 'google;apple',
      includeDescription: 'blockchain;security',
      excludeDescription: 'intern;fresher;junior;entry',
      active: false,
    },
  ],
};
export default MOCK;
