export const mockJobData = [
  {
    id: 1,
    company: 'Google',
    level: 'Senior',
    date: '1 MAY, 2024',
    salary: '$120k - $150k',
    logo: 'https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png',
    title: 'Software Engineer',
    location: 'Mountain View, CA',
    arrangement: 'Remote',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 2,
    company: 'Facebook',
    level: 'Mid',
    date: '1 MAY, 2024',
    salary: '$100k - $120k',
    logo: 'https://cdn1.iconfinder.com/data/icons/social-media-2285/512/Colored_Facebook3_svg-256.png',
    title: 'Frontend Engineer',
    location: 'Menlo Park, CA',
    arrangement: 'On-site',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 3,
    company: 'Amazon',
    level: 'Junior',
    date: '1 MAY, 2024',
    salary: '$80k - $100k',
    logo: 'https://cdn3.iconfinder.com/data/icons/social-media-2169/24/social_media_social_media_logo_amazon-256.png',
    title: 'Cloud Engineer',
    location: 'Seattle, WA',
    arrangement: 'Hybrid',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 4,
    company: 'Microsoft',
    level: 'Intern',
    date: '1 MAY, 2024',
    salary: '$120k - $150k',
    logo: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/216_Microsoft_logo_logos-256.png',
    title: '.NET Developer',
    location: 'Redmond, WA',
    arrangement: 'Remote',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 5,
    company: 'Apple',
    level: 'Mid',
    date: '1 MAY, 2024',
    salary: '$100k - $120k',
    logo: 'https://cdn4.iconfinder.com/data/icons/flat-brand-logo-2/512/apple-256.png',
    title: 'IOS Engineer',
    location: 'Cupertino, CA',
    arrangement: 'On-site',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 1,
    company: 'Google',
    level: 'Senior',
    date: '1 MAY, 2024',
    salary: '$120k - $150k',
    logo: 'https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png',
    title: 'Software Engineer',
    location: 'Mountain View, CA',
    arrangement: 'Remote',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 2,
    company: 'Facebook',
    level: 'Mid',
    date: '1 MAY, 2024',
    salary: '$100k - $120k',
    logo: 'https://cdn1.iconfinder.com/data/icons/social-media-2285/512/Colored_Facebook3_svg-256.png',
    title: 'Frontend Engineer',
    location: 'Menlo Park, CA',
    arrangement: 'On-site',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 3,
    company: 'Amazon',
    level: 'Junior',
    date: '1 MAY, 2024',
    salary: '$80k - $100k',
    logo: 'https://cdn3.iconfinder.com/data/icons/social-media-2169/24/social_media_social_media_logo_amazon-256.png',
    title: 'Cloud Engineer',
    location: 'Seattle, WA',
    arrangement: 'Hybrid',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 4,
    company: 'Microsoft',
    level: 'Intern',
    date: '1 MAY, 2024',
    salary: '$120k - $150k',
    logo: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/216_Microsoft_logo_logos-256.png',
    title: '.NET Developer',
    location: 'Redmond, WA',
    arrangement: 'Remote',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 5,
    company: 'Apple',
    level: 'Mid',
    date: '1 MAY, 2024',
    salary: '$100k - $120k',
    logo: 'https://cdn4.iconfinder.com/data/icons/flat-brand-logo-2/512/apple-256.png',
    title: 'IOS Engineer',
    location: 'Cupertino, CA',
    arrangement: 'On-site',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 1,
    company: 'Google',
    level: 'Senior',
    date: '1 MAY, 2024',
    salary: '$120k - $150k',
    logo: 'https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png',
    title: 'Software Engineer',
    location: 'Mountain View, CA',
    arrangement: 'Remote',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 2,
    company: 'Facebook',
    level: 'Mid',
    date: '1 MAY, 2024',
    salary: '$100k - $120k',
    logo: 'https://cdn1.iconfinder.com/data/icons/social-media-2285/512/Colored_Facebook3_svg-256.png',
    title: 'Frontend Engineer',
    location: 'Menlo Park, CA',
    arrangement: 'On-site',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 3,
    company: 'Amazon',
    level: 'Junior',
    date: '1 MAY, 2024',
    salary: '$80k - $100k',
    logo: 'https://cdn3.iconfinder.com/data/icons/social-media-2169/24/social_media_social_media_logo_amazon-256.png',
    title: 'Cloud Engineer',
    location: 'Seattle, WA',
    arrangement: 'Hybrid',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 4,
    company: 'Microsoft',
    level: 'Intern',
    date: '1 MAY, 2024',
    salary: '$120k - $150k',
    logo: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/216_Microsoft_logo_logos-256.png',
    title: '.NET Developer',
    location: 'Redmond, WA',
    arrangement: 'Remote',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 5,
    company: 'Apple',
    level: 'Mid',
    date: '1 MAY, 2024',
    salary: '$100k - $120k',
    logo: 'https://cdn4.iconfinder.com/data/icons/flat-brand-logo-2/512/apple-256.png',
    title: 'IOS Engineer',
    location: 'Cupertino, CA',
    arrangement: 'On-site',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 1,
    company: 'Google',
    level: 'Senior',
    date: '1 MAY, 2024',
    salary: '$120k - $150k',
    logo: 'https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png',
    title: 'Software Engineer',
    location: 'Mountain View, CA',
    arrangement: 'Remote',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 2,
    company: 'Facebook',
    level: 'Mid',
    date: '1 MAY, 2024',
    salary: '$100k - $120k',
    logo: 'https://cdn1.iconfinder.com/data/icons/social-media-2285/512/Colored_Facebook3_svg-256.png',
    title: 'Frontend Engineer',
    location: 'Menlo Park, CA',
    arrangement: 'On-site',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 3,
    company: 'Amazon',
    level: 'Junior',
    date: '1 MAY, 2024',
    salary: '$80k - $100k',
    logo: 'https://cdn3.iconfinder.com/data/icons/social-media-2169/24/social_media_social_media_logo_amazon-256.png',
    title: 'Cloud Engineer',
    location: 'Seattle, WA',
    arrangement: 'Hybrid',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 4,
    company: 'Microsoft',
    level: 'Intern',
    date: '1 MAY, 2024',
    salary: '$120k - $150k',
    logo: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/216_Microsoft_logo_logos-256.png',
    title: '.NET Developer',
    location: 'Redmond, WA',
    arrangement: 'Remote',
    type: 'Full-time',
    industry: 'IT & Media',
  },
  {
    id: 5,
    company: 'Apple',
    level: 'Mid',
    date: '1 MAY, 2024',
    salary: '$100k - $120k',
    logo: 'https://cdn4.iconfinder.com/data/icons/flat-brand-logo-2/512/apple-256.png',
    title: 'IOS Engineer',
    location: 'Cupertino, CA',
    arrangement: 'On-site',
    type: 'Full-time',
    industry: 'IT & Media',
  },
];

export const mockJobTypeOptions = [
  { label: 'Full-time', value: 'full_time' },
  { label: 'Part-time', value: 'part_time' },
  { label: 'Internship', value: 'internship' },
  { label: 'Contract', value: 'contract' },
  { label: 'Freelance', value: 'freelance' },
];

export const mockJobIndustryOptions = [
  { label: 'IT & Media', value: 'it_media' },
  { label: 'Finance', value: 'finance' },
  { label: 'Health', value: 'health' },
  { label: 'Education', value: 'education' },
];

export const mockJobLevelOptions = [
  { label: 'Senior', value: 'senior' },
  { label: 'Mid', value: 'mid' },
  { label: 'Junior', value: 'junior' },
];

export const mockJobArrangementOptions = [
  { label: 'Remote', value: 'remote' },
  { label: 'On-site', value: 'on_site' },
  { label: 'Hybrid', value: 'hybrid' },
  { label: 'Flexible', value: 'flexible' },
];
