const MOCK = {
  JOBS: [
    {
      id: 1,
      company: 'Google',
      level: 'Senior',
      date: '1 MAY, 2024',
      salary: '$120k - $150k',
      logo: 'https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png',
      title: 'Software Engineer',
      location: 'Mountain View, CA',
      arrangement: 'Remote',
      type: 'Full-time',
      industry: 'IT & Media',
    },
    {
      id: 2,
      company: 'Facebook',
      level: 'Mid',
      date: '1 MAY, 2024',
      salary: '$100k - $120k',
      logo: 'https://cdn1.iconfinder.com/data/icons/social-media-2285/512/Colored_Facebook3_svg-256.png',
      title: 'Frontend Engineer',
      location: 'Menlo Park, CA',
      arrangement: 'On-site',
      type: 'Full-time',
      industry: 'IT & Media',
    },
    {
      id: 3,
      company: 'Amazon',
      level: 'Junior',
      date: '1 MAY, 2024',
      salary: '$80k - $100k',
      logo: 'https://cdn3.iconfinder.com/data/icons/social-media-2169/24/social_media_social_media_logo_amazon-256.png',
      title: 'Cloud Engineer',
      location: 'Seattle, WA',
      arrangement: 'Hybrid',
      type: 'Full-time',
      industry: 'IT & Media',
    },
    {
      id: 4,
      company: 'Microsoft',
      level: 'Intern',
      date: '1 MAY, 2024',
      salary: '$120k - $150k',
      logo: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/216_Microsoft_logo_logos-256.png',
      title: '.NET Developer',
      location: 'Redmond, WA',
      arrangement: 'Remote',
      type: 'Full-time',
      industry: 'IT & Media',
    },
    {
      id: 5,
      company: 'Apple',
      level: 'Mid',
      date: '1 MAY, 2024',
      salary: '$100k - $120k',
      logo: 'https://cdn4.iconfinder.com/data/icons/flat-brand-logo-2/512/apple-256.png',
      title: 'IOS Engineer',
      location: 'Cupertino, CA',
      arrangement: 'On-site',
      type: 'Full-time',
      industry: 'IT & Media',
    },
  ],
  OPTIONS: {
    TIME: [
      { value: 'ANY', label: 'Any' },
      { value: 'DAY', label: 'Day' },
      { value: 'WEEK', label: 'Week' },
      { value: 'MONTH', label: 'Month' },
    ],
    TYPE: [
      { value: 'FULL_TIME', label: 'Full-Time' },
      { value: 'PART_TIME', label: 'Part-Time' },
      { value: 'TEMPORARY', label: 'Temporary' },
      { value: 'CONTRACT', label: 'Contract' },
      { value: 'INTERNSHIP', label: 'Internship' },
      { value: 'VOLUNTEER', label: 'Volunteer' },
      { value: 'OTHER', label: 'Other' },
    ],
    INDUSTRY: [
      { value: 'TECHNOLOGY_INFORMATION_AND_MEDIA', label: 'IT & Media' },
      { value: 'ACCOMMODATION_SERVICES', label: 'Accommodation' },
      { value: 'ADMINISTRATIVE_AND_SUPPOR_SERVICES', label: 'Admin Support' },
      { value: 'CONSTRUCTION', label: 'Construction' },
      { value: 'CONSUMER_SERVICES', label: 'Consumer Services' },
      { value: 'EDUCATION', label: 'Education' },
      { value: 'ENTERTAINMENT_PROVIDERS', label: 'Entertainment' },
      { value: 'FARMING_RANCHING_FORESTRY', label: 'Farming' },
      { value: 'FINANCIAL_SERVICES', label: 'Financial' },
      { value: 'GOVERNMENT_ADMINISTRATION', label: 'Government' },
      { value: 'HOSPITALS_AND_HEALTH_CARE', label: 'Health Care' },
      { value: 'MANUFACTURING', label: 'Manufacturing' },
      { value: 'PROFESSIONAL_SERVICES', label: 'Professional' },
      {
        value: 'REAL_ESTATE_AND_EQUIPMENT_RENTAL_SERVICES',
        label: 'Real Estate',
      },
      { value: 'RETAIL', label: 'Retail' },
    ],
    EXP_LEVEL: [
      { value: 'INTERNSHIP', label: 'Intern' },
      { value: 'ENTRY_LEVEL', label: 'Entry' },
      { value: 'ASSOCIATE', label: 'Associate' },
      { value: 'MID_SENIOR', label: 'Mid-Senior' },
      { value: 'DIRECTOR', label: 'Director' },
      { value: 'EXECUTIVE', label: 'Executive' },
    ],
    WORKING_MODE: [
      { value: 'ON_SITE', label: 'On-Site' },
      { value: 'REMOTE', label: 'Remote' },
      { value: 'HYBRID', label: 'Hybrid' },
    ],
  },
  FILTERS: [
    {
      id: 1,
      name: 'Default',
      user: '60f9f1b6d9f7c8000f0f3b1d',
      location: 'Mountain View, CA',
      keyword: 'Software Engineer',
      experience_level: 'MID_SENIOR',
      working_mode: 'REMOTE',
      type: 'FULL_TIME',
      industry: ['TECHNOLOGY_INFORMATION_AND_MEDIA'],
      time: 'DAY',
      excludeTitles: 'senior;lead',
      excludeCompanies: 'netflix;facebook',
      includeDescription: 'ai;developer',
      excludeDescription: 'senior;lead',
      active: true,
    },
    {
      id: 2,
      name: 'Frontend Dev',
      user: '60f9f1b6d9f7c8000f0f3b1d',
      location: 'Menlo Park, CA',
      keyword: 'Frontend Engineer',
      experience_level: 'ENTRY_LEVEL',
      working_mode: 'ON_SITE',
      type: 'FULL_TIME',
      industry: ['TECHNOLOGY_INFORMATION_AND_MEDIA'],
      time: 'WEEK',
      excludeTitles: 'senior;lead',
      excludeCompanies: 'google;apple',
      includeDescription: 'blockchain;security',
      excludeDescription: 'intern;fresher;junior;entry',
      active: false,
    },
  ],
};

export default MOCK;
